version: '3.1'
services:
  tomcat:
     restart: always
     image: tomcat
     container_name: tomcat
     ports:
       - 8081:8080
     volumes:
       - ./webapps:/usr/local/tomcat/webapps
       - ./root:/etc/guacamole
     environment:
       TZ: Asia/Shanghai
