version: '3.1'
services:
  tomcat:
     restart: always
     image: osixia/openldap:1.3.0
     container_name: myldap
     ports:
       - 389:389
       - 636:636 
     volumes:
       - ./root:/root
